'use client';

import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Header 
        onLoginClick={() => {}}
        userLocation={null}
        onLocationChange={() => {}}
      />
      
      <div className="py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-lg shadow-sm p-8">
            <div className="text-center mb-8">
              <h1 className="text-3xl font-bold text-gray-900 mb-4">Terms and Conditions for Fixigo Service Providers</h1>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-blue-800 font-medium">Call for More Info</p>
                <p className="text-blue-900 text-lg font-bold">📞 040 – 32325246</p>
              </div>
            </div>
            
            <div className="prose max-w-none">
              <p className="text-gray-600 mb-6">
                These terms and conditions ("Terms") govern the use of services made available on or through https://fixigo.com and/or the Fixigo mobile app (collectively, the "Platform", and together with the services made available on or through the Platform, the "Services"). These Terms include any guidelines, additional, or supplemental terms, policies, and disclaimers issued by us from time to time ("Supplemental Terms"). The Privacy Policy and the Supplemental Terms form an integral part of these Terms. In the event of a conflict between these Terms and the Supplemental Terms with respect to applicable Services, the Supplemental Terms will prevail.
              </p>

              <p className="text-gray-600 mb-8">
                The Terms constitute a binding and enforceable legal contract between Fixigo Services Private Limited (a company incorporated under the Companies Act, 2013, with its registered address at [insert registered address], and its affiliates ("Fixigo", "we", "us", or "our")), and you, a user of the Services, or any legal entity that books services (defined below) on behalf of end-users ("you" or "Service Provider"). By using the Services, you represent and warrant that you have full legal capacity and authority to agree to and bind yourself to these Terms. If you represent any other person, you confirm and represent that you have the necessary power and authority to bind that person to these Terms.
              </p>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">Electronic Record</h2>
                <p className="text-gray-600">
                  This document shall constitute and be deemed to be an electronic record as defined and in accordance with the provisions of the Information Technology Act, 2000 and the rules made thereunder, applicable to electronic records, as well as any amended provisions including but not limited to legislations stipulated in various statutes relating to electronic records. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">Publication</h2>
                <p className="text-gray-600">
                  This document is being published on www.fixigo.com and the Fixigo Mobile Application in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Introduction</h2>
                <p className="text-gray-600 mb-3">Fixigo is an aggregator platform that connects customers with verified service providers for:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Appliance repair (AC, washing machine, fridge, microwave, etc.)</li>
                  <li>Cleaning (deep cleaning, sofa cleaning, home cleaning, office cleaning, etc.)</li>
                  <li>Pest control services</li>
                  <li>Electrical, plumbing, carpentry, handyman, and painting services</li>
                  <li>Other home needs and professional services</li>
                </ul>
                <p className="text-gray-600 mt-4">We act as a technology facilitator. The actual service is carried out by independent providers registered on our platform.</p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">2. Eligibility</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Customers must be 18 years or older to book services.</li>
                  <li>Service providers must submit: Aadhaar, PAN, police verification, experience proof, and bank details.</li>
                  <li>By creating an account, you warrant that the information provided is true, accurate, and updated.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">3. User Accounts</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Customers and providers must register with a valid phone number/email.</li>
                  <li>You are responsible for all actions carried out under your account.</li>
                  <li>Fixigo is not liable for misuse of accounts due to password/OTP sharing.</li>
                  <li>We may suspend or terminate accounts for fraudulent or abusive activity.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Verification of Service Providers</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Providers undergo identity checks, Aadhaar OTP verification, and PAN validation.</li>
                  <li>Providers must maintain updated documents. Failure to do so may lead to account suspension.</li>
                  <li>Providers must use a profile photo to build trust with customers.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Services Offered</h2>
                <p className="text-gray-600 mb-3">Services are provided at the customer's location at the scheduled time. Providers must:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Arrive on time and in proper attire.</li>
                  <li>Deliver services professionally and ethically.</li>
                  <li>Use approved tools, materials, and safe methods.</li>
                  <li>Providers must not solicit cash, tips, or direct payments outside the Fixigo platform.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">6. Pricing, Payments & Invoicing</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Pricing will be displayed on the Platform before booking.</li>
                  <li>Customers agree to pay via: UPI, cards, net banking, wallets, or cash (if allowed).</li>
                  <li>Providers are paid through Fixigo's secure system after deducting platform fees & GST.</li>
                  <li>Any extra services or spare parts must be pre-approved via Fixigo support.</li>
                  <li>Invoices will be generated digitally and shared with customers.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">7. Refunds & Cancellations</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Customers may cancel a booking before service dispatch without penalty.</li>
                  <li>If cancelled after technician dispatch, a visit/cancellation fee may apply.</li>
                  <li>Refunds for prepaid services will be processed within 7-10 working days to the original payment method.</li>
                </ul>
                <p className="text-gray-600 mt-4 mb-3">No refunds will be made if:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Customer provides wrong address/contact details.</li>
                  <li>Service is denied after provider arrival.</li>
                  <li>Service is completed as per scope.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">8. Service Warranties</h2>
                <p className="text-gray-600 mb-3">Certain services (e.g., appliance repair, pest control) may include a limited service warranty (e.g., 7–30 days) as communicated during booking. Warranty is void if:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Customer tampers with the repaired appliance.</li>
                  <li>Service is altered by an unauthorized third party.</li>
                  <li>Chemicals or spare parts are misused.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">9. Customer Responsibilities</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Ensure safe access to the premises.</li>
                  <li>Do not request services outside the booked scope.</li>
                  <li>Keep valuables secure. Fixigo and providers are not liable for loss of personal property unless proven negligent.</li>
                  <li>Customers must not engage in verbal or physical abuse towards service providers.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">10. Insurance & Damages</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Providers are responsible for damages caused by negligence during service.</li>
                  <li>Customers must report damages within 24 hours of service completion.</li>
                  <li>Fixigo may facilitate mediation, but final liability lies with the provider.</li>
                  <li>Fixigo does not provide insurance unless explicitly stated in the service description.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">11. Order Allocation</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Orders are allocated based on location and availability.</li>
                  <li>Providers must accept within 2 minutes of notification.</li>
                  <li>Repeated rejections may lead to account restrictions.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">12. Rescheduling</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Customers can request rescheduling through the app or customer support.</li>
                  <li>Providers may reschedule only for valid reasons with prior customer approval.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">13. Termination & Suspension</h2>
                <p className="text-gray-600 mb-3">Fixigo reserves the right to suspend/terminate accounts for:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Fraudulent activity.</li>
                  <li>Violating these Terms.</li>
                  <li>Customer complaints of misconduct.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">14. Intellectual Property</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>All content (logos, images, software, website, app) is owned by Fixigo.</li>
                  <li>You must not copy, distribute, or misuse Fixigo's intellectual property.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">15. Limitation of Liability</h2>
                <p className="text-gray-600 mb-3">Fixigo is a platform provider, not the direct service provider. We are not liable for:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Delays due to traffic, weather, or emergencies.</li>
                  <li>Provider misconduct.</li>
                  <li>Customer's misuse of services.</li>
                </ul>
                <p className="text-gray-600 mt-4">Our liability, if proven, will be limited to the amount paid for the disputed booking.</p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">16. Dispute Resolution</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Complaints must be raised via Fixigo support within 48 hours.</li>
                  <li>Disputes shall first be attempted to be resolved through mediation.</li>
                  <li>If unresolved, disputes will be referred to arbitration under the Arbitration and Conciliation Act, 1996 in Hyderabad, Telangana.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">17. Force Majeure</h2>
                <p className="text-gray-600 mb-3">Fixigo will not be responsible for delays or failure in services caused by events beyond our control, including:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Natural disasters</li>
                  <li>Strikes or labor disputes</li>
                  <li>Internet/telecom failures</li>
                  <li>Government actions or restrictions</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">18. Amendments</h2>
                <p className="text-gray-600">
                  Fixigo may update these Terms at any time. Changes will be effective immediately upon posting on the Platform. Continued use of services indicates acceptance.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">19. Governing Law</h2>
                <p className="text-gray-600">
                  These Terms are governed by the laws of India. Courts in Hyderabad, Telangana will have exclusive jurisdiction.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">20. Acknowledgment</h2>
                <p className="text-gray-600">
                  By using Fixigo Services, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions, including any future updates or modifications.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">21. Contact Us</h2>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>📧 Email: support@fixigo.com</li>
                  <li>📞 Phone: 040 - 32325246</li>
                </ul>
              </section>

              <div className="text-center mt-12 pt-8 border-t border-gray-200">
                <p className="text-gray-600 mb-4">© 2025 Fixigo Services Pvt. Ltd. All Rights Reserved.</p>
                <div className="flex justify-center space-x-4 text-sm">
                  <span className="text-blue-600">🔹 Terms of Use</span>
                  <span className="text-gray-400">|</span>
                  <a href="/refund-policy" className="text-blue-600 hover:underline">Refund Policy</a>
                  <span className="text-gray-400">|</span>
                  <a href="/privacy-policy" className="text-blue-600 hover:underline">Privacy Policy</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <Footer />
    </div>
  );
}